---
title: "filter_and_plot_output.Rmd"
author: "Laura Puckett"
date: "10/17/2020"
output: html_document
---

## 1. Packages
```{r, echo = F}
library(dplyr); library(ggplot2)
working_dir = '/Volumes/cirrus/scratch/lkp58/lidar_comparisons/'
icesat2_data_path = './sites/NEON_BONA/data/icesat2/3_comparison.csv'
```

## 2. Parameters

```{r, echo=FALSE}
icesat2_strong_beams = c("1l","2l","3l")
can_uncert_threshold = 50
```

## 3. Filter Icesat2 Data
```{r, echo=FALSE}
setwd(working_dir)
icesat2_data_full = read.csv(icesat2_data_path, stringsAsFactors = F)
colnames(icesat2_data_full)
nrow(icesat2_data_full)

icesat2_filtered = icesat2_data_full %>%
  rename(
    night_flag = nght_fl) %>%
  mutate(sensor = "icesat2") %>%
  filter(night_flag == 1 &
           toc_pho > 0 &
           beam %in% icesat2_strong_beams) 
nrow(icesat2_filtered)
```

## 5. Combine and Write Output File
```{r, echo=FALSE}
setwd(working_dir)

icesat2_for_combined_df = icesat2_filtered %>%
  rename(latitude = lat,
         longitude = lon,
         sens_rh_100 = cn_max,
         sens_rh_98 = h_can,
         sens_rh_95 = cn_h_95) %>%
  mutate(ALS_grid_gauss = NA) %>%
  select(sens_rh_100, sens_rh_98, sens_rh_95,
         RH_100_ALS, RH_98_ALS, RH_95_ALS,
         ALS_all_grid, ALS_abvg_grid, ALS_grid_gauss, 
         sensor, longitude, latitude)

data = icesat2_for_combined_df

```

## 5. Figures
```{r, echo=FALSE}
setwd(working_dir)
vars = c("ALS_abvg_grid",
         "ALS_all_grid",
         "ALS_grid_gauss",
         "RH_98_ALS",
         "RH_95_ALS")

# for(var in vars){
  ggplot(data, aes(x = RH_98_ALS, y = sens_rh_98))+
    geom_point(alpha = 0.1) +
    theme_bw() +
    coord_fixed(xlim = c(0,50), ylim = c(0,50)) +
    xlab("NEON Canopy Height [m]") +
    ylab("Icesat-2 Canopy Height [m]") + 
    geom_smooth(aes(x = RH_98_ALS, y = sens_rh_98),method = "lm", formula = y~x, se = FALSE, color = "blue") +
    ggpmisc::stat_poly_eq(aes(x = RH_98_ALS, y = sens_rh_98, label =  paste(stat(eq.label), stat(adj.rr.label), sep = "~~~~")),
                          formula = y~x, parse = TRUE,
                          label.y = "top", label.x = "right")
# }


# ctg = lidR::readLAScatalog('./sites/NEON_BONA/data/als/0_dl/DP1.30003.001/2019/FullSite/D19/2019_BONA_3/L1/DiscreteLidar/ClassifiedPointCloud/')
# dtm = lidR::grid_terrain(ctg,
#                   res = 100,
#                   algorithm = tin())
```

```{r}
library(sp)
library(raster)
site = rgdal::readOGR('./sites/NEON_BONA/boundary/BONA.shp')
footprints = rgdal::readOGR('./sites/NEON_BONA/data/icesat2/2_geometries.shp')
filtered_footprints = footprints[footprints$X %in% icesat2_filtered$X,]
```

```{r}
plot(site)
plot(filtered_footprints, add = T, border = "blue")


```